name: "Restore npm cache"
description: ""
runs:
  using: composite
  steps:
    - uses: actions/cache@v2
      env:
        cache-name: npm-deps-v1
      with:
        path: |
          ~/.npm
          ./node_modules
        key: ${{ env.cache-name }}-${{ hashFiles( 'package-lock.json' ) }}
        restore-keys: |
          ${{ env.cache-name }}-